language: ruby
bundler_args: --without production

rvm:
  - "2.0.0"

env:
- DB=postgresql
- TAG_FILTER=~js DB=postgres RAILS_ENV=test
- TAG_FILTER=js DB=postgres RAILS_ENV=test
install: touch ~/do_not_run_bundle

before_script:
  - psql -c 'create database metagame_test' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - "./script/travis/setup_database.sh &"
  - "./script/travis/configure_rspec.sh &"
  - "./script/travis/bundle_install.sh"
  - "bundle exec ruby script/travis/bundle_cache.rb &"

script:
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
	"bundle exec rspec --tag $TAG_FILTER && sleep 1"


notifications:
  email: false